### ISSUE TITLE
could you help me with this case !

### ISSUE THREAD

**Issue by drupalshift** [twg/devour#123]
Hi 

I'm trying to request this public jsonapi url 

```javascript
const JsonApi = require('devour-client')

const jsonApi = new JsonApi({apiUrl: 'https://live-contentacms.pantheonsite.io/api/'})

jsonApi.define('recipes', {
  title: ''
})

console.log(jsonApi.findAll('recipes'))
```

I'm getting this error stack an a big object which is not the title of recipes 

```bash
Promise {
  '': 10,
  _state: undefined,
  _result: undefined,
  _subscribers: [] }
devour error { Error: Request failed with status code 404
    at createError (/home/hamed/Projects/grizzly/contenta_vue_nuxt/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/hamed/Projects/grizzly/contenta_vue_nuxt/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/hamed/Projects/grizzly/contenta_vue_nuxt/node_modules/axios/lib/adapters/http.js:191:11)
    at IncomingMessage.emit (events.js:132:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

What am i doning wrong here !?

**Comment by spiderbites** [comment]
Hey @drupalshift, try defining your resource using the singular `recipe` and also supplying your api url without the trailing slash.
